#!/usr/bin/env python3

import random
import colors as c





answers = [ c.g + 'yes' + c.x,
c.r + "No" + c.x,
c.g + 'Theres a 99% chance' + c.x,
c.r + 'NEVER!' + c.x,
c.c + 'let me see...' + c.x,
c.v + 'What?' +  c.x,
c.v + 'Ask Siri' + c.x,
c.g + 'I sence it' +  c.x,
c.r + 'Only a 1% chance' + c.x,
c.v + """There was once a pig named Gizmo, who always dreamed of becoming a  unicorn.
One day it rained cows and his chance came he followed his dream..""" + c.x,
c.v + "I like gerbls" + c.x,
c.v + "Maybe..." + c.x,
c.r + "WHAT ARE YOU THINKING NO!!" + c.x,
c.g + "Of course!!" + c.x,
c.m + "LOL why not!" + c.x,
c.m + " <3" + c.x,
c.r + "#NEVER!" + c.x,
c.g + "#YEA!" + c.x,
c.c + "#Tell y'a later" + c.x,
c.r + "Nope" + c.x,
c.g + "Yea" + c.x,
c.m + "M" + c.o + "e" + c.m + "o" + c.o + "w" + c.x,
c.r + 'No' +  c.x, 
c.c + 'What do u think?' +  c.x,
c.c + 'Sorry, Im playing minecraft right now' + c.x,
c.g + 'Are you crazy, of course!' + c.x,
c.g + "Honestly, Yes" + c.x,
c.r + "Honestly, No" + c.x,
c.r + "#No4ever" + c.x,
c.r + "IM NOT UR FRIEND" + c.x,
]

def welcome():
    print( c.clear +  c.v +  """
    Welcome to the #magic""" + c.rc() +  """ 8""" +  c.v + """ ball
    Enter your question below!""")

def ask(prompt):
    answer = input(prompt).strip().lower()
    return answer
def bye():
    print("Bye! Hope to see u soon!")
    exit()
try:
     welcome()
     while True:
        question = ask( c.m + '-----> ' + c.y)
        if question == 'bye' or question == 'goodbye':
             bye()
        elif "death" in question or "die" in question:
            print(c.base3 + "Sorry can not predict death @xxxx[{:::::::::::::::::::::>" + c.x )
        elif "love" in question:
            print(c.m + "I sence love secrets..." + c.x)
        elif "pinksheep" in question or "pink sheep" in question:
            print(c.m + "For it is I the Pink Sheep plz join my server I am the wonderfull mascott")
        elif "nyan" in question or "nyancat" in question:
            print(c.m + """
                            +      o     +              o   
                                +             o     +       +
                                o          +
                                    o  +           +        +
                              +        o     o       +        o
                                 -_-_-_-_-_-_-_,------,      o 
                                 _-_-_-_-_-_-_-|   /\_/\  
                                 -_-_-_-_-_-_-~|__( ^ .^)  +     +  
                                 _-_-_-_-_-_-_-""  ""      
                                 +      o         o   +       o
                                 +         +
                                 o        o         o      o     +
                                +      +     o        o      +    """ + c.x )
        elif "10" in question:
            print(c.o + "Thats My Lucky Number" + c.x )
        else:
            answer = random.choice(answers)
            print( c.x + answer) 
except KeyboardInterrupt:
   print()
   bye()
