#!/usr/bin/env python3

import random
import colors as c

print( c.clear +  c.v +  """
Welcome to the #magic""" + c.rc() +  """ 8""" +  c.v + """ ball
Enter your question below!""")

answers = [ c.g + 'yes' + c.x,
c.r + 'No' +  c.x, 
c.c + 'What do u think?' +  c.x,
c.c + 'Sorry, Im playing minecraft right now' + c.x,
c.g + 'Are you crazy, of course!' + c.x,
c.g + 'Theres a 99% chance' + c.x,
c.r + 'NEVER!' + c.x,
c.c + 'let me see...' + c.x,
c.v + 'What?' +  c.x,
c.v + 'Ask Siri' + c.x,
c.g + 'I sence it' +  c.x,
c.r + 'Only a 1% chance' + c.x,
c.v + """There was once a pig named Gizmo, who always dreamed of becoming a  unicorn.
One day it rained meteors and his chance came he followed his dream...""" + c.x,
c.v + "I like gerbls" + c.x,
c.v + "Maybe..." + c.x,
c.r + "WHAT ARE YOU THINKING NO!!" + c.x,
c.g + "Of course!!" + c.x,
c.m + "LOL why not!" + c.x,
c.m + " <3" + c.x,
c.r + "#NEVER!" + c.x,
c.g + "#YEA!" + c.x,
c.c + "#Tell y'a later" + c.x,
]

try:
     while True:
        question = input( c.m + '-----> ' + c.y)
        if "death" in question or "die" in question or "Death" in question or "Die" in question:
            print(c.base3 + "Sorry can not predict death" + c.x )
        elif "love" in question or "Love" in question:
            print(c.m + "I sence love secrets..." + c.x)
        answer = random.choice(answers)
        print( c.x + answer)
         
