#!/usr/bin/env python3

import colors as c
print(c.rc() +  "Hi," +  c.rc() + " what's" +  c.rc() + " your" +  c.rc() + " name?")
name = input(c.o + '--> ' + c.m)
print(c.rc() + "Hello" + c.rc() + " there, " + c.rc() + name )

